SELECT TO_CHAR(ADD_MONTHS(TO_DATE(SALMONTH, 'YYYYMM'),1), 'YYYYMM')  
--SALMONTH가 CHAR 타입이기 떄문에 TO_DATE로 형변환,  ADD_MONTHS()의 데이터 타입은 DATE임
--그리고 ADD_MONTHS을 TO_CHAR로 데이터 형변환해줌
    FROM SALARY
    WHERE SALMONTH = (SELECT MAX(SALMONTH) FROM SALARY);